#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

maxLimit = 4000000

fibLow = 1
fibHigh = 2
fibCur = 1 
sumOfEven = 0

while (fibCur < maxLimit):
    fibLow = fibHigh
    if (fibCur % 2 == 0):
        sumOfEven += fibCur
    fibHigh += fibCur
    fibCur = fibLow

print sumOfEven
